the_weather/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^history_filtered', views.filtered_history, name='filtered_history'),

]

weather/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('the_weather.urls', namespace='weather')),


]

the_weather/models.py
from django.db import models


class ExistCity(models.Model):
    CITY_CHOICES = (
        ('London', 'London'),
        ('Tokyo', 'Tokyo'),
        ('New York', 'New York'),
        ('Liverpool', 'Liverpool'),
        ('Kyiv', 'Kyiv'),
        ('Vinnytsia','Vinnytsia'),
        ('Las Vegas', 'Las Vegas'),
        ('Donetsk', 'Donetsk'),
        ('Lviv', 'Lviv'),
        ('Baku', 'Baku'),
        ('Moscow', 'Moscow'),
        ('Sevastopol', 'Sevastopol'),
        ('Paris', 'Paris'),
    )

    name = models.CharField(max_length=30, choices=CITY_CHOICES, blank=True)

    def __str__(self):
        return self.name


class NewCity(models.Model):

    name = models.CharField(max_length=30)
    temperature = models.FloatField(default=0)
    description = models.CharField(max_length=40,blank=True)
    icon = models.CharField(max_length=10, blank=True)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

the_weather/forms.py
from django.forms import ModelForm, TextInput, Form
from .models import ExistCity, NewCity
from django import forms


class SelectCityForm(ModelForm):
    class Meta:
        model = ExistCity
        fields = ['name']

    CITY_CHOICES = (
        ('London', 'London'),
        ('Tokyo', 'Tokyo'),
        ('New York', 'New York'),
        ('Liverpool', 'Liverpool'),
        ('Kyiv', 'Kyiv'),
        ('Vinnytsia', 'Vinnytsia'),
        ('Las Vegas', 'Las Vegas'),
        ('Donetsk', 'Donetsk'),
        ('Lviv', 'Lviv'),
        ('Baku', 'Baku'),
        ('Moscow', 'Moscow'),
        ('Sevastopol', 'Sevastopol'),
        ('Paris', 'Paris'),
    )
    name = forms.ChoiceField(choices=CITY_CHOICES, label="", initial='', widget=forms.Select(), required=False)
    widgets = {'name': TextInput(attrs={'class': 'select', 'placeholder': 'Input City name'})}


class InputCityForm(ModelForm):
    class Meta:
        model = NewCity
        fields = ['name']
        widgets = {'name': TextInput(attrs={'class': 'select', 'placeholder': 'Input City name'})}

the_weather/views.py
from django.shortcuts import render
import requests
from .forms import SelectCityForm, InputCityForm
from .models import ExistCity, NewCity
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from.filters import CityFilter
# Create your views here.


def home(request):
    url = 'http://api.openweathermap.org/' \
          'data/2.5/weather?q={}&units=metric&' \
          'appid=c570c535821c0558cceee4b7a9649e95'
    if request.POST:
        form = InputCityForm(request.POST)
        city = form.data['name']
        req = requests.get(url.format(city)).json()
        if req['cod'] == 200:
            city_data = form.save(commit=False)
            city_data.name = city
            city_data.temperature = req['main']['temp']
            city_data.icon = req['weather'][0]['icon']
            city_data.description = req['weather'][0]['description']
            form.save()

            weather = {
                'city': city,
                'temperature': req['main']['temp'],
                'description': req['weather'][0]['description'],
                'icon': req['weather'][0]['icon'],
            }
            inputform = InputCityForm()
            selectform = SelectCityForm()
            context = {'weather': weather,
                       'inputform': inputform,
                       'selectform': selectform,
                       }

            return render(request, 'home_page.html', context)
        else:
            inputform = InputCityForm()
            selectform = SelectCityForm()
            context = {'inputform': inputform,
                       'selectform': selectform,
                       'error': 'true'}
            return render(request, 'home_page.html', context)

    else:
        inputform = InputCityForm()
        selectform = SelectCityForm()
        context = {'inputform': inputform,
                   'selectform': selectform}
        return render(request, 'home_page.html', context)


def filtered_history(request):
    city_filtered = CityFilter(
            request.GET,
            queryset=NewCity.objects.all().order_by("-date_created")
        )

    paginator = Paginator(city_filtered.qs, 10)  # Show 10  per page
    page_request_var = 'page'
    page = request.GET.get(page_request_var)

    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        queryset = paginator.page(1)
    except EmptyPage:
        queryset = paginator.page(paginator.num_pages)

    context = {
        'filter': city_filtered,
        'weather': queryset,
        'page_request_var': page_request_var,
        }
    return render(request, 'filtered_history.html', context)

the_weather/templates/base.html
<!--{% load static from staticfiles %}-->
<!DOCTYPE html>

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Weather</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.2/css/bulma.css" />
</head>

<body>
    <section class="hero is-primary">
        <div class="hero-body">
            <div class="container">
                <h1 class="title">
                   {% block greetings %}
                   {% endblock greetings %}
                </h1>
            </div>
        </div>
    </section>



    <section class="section">
        <div class="container">
            <div class="columns">
                <div class="column is-offset-4 is-4">


                      {% block content %}


                      {% endblock content %}





                 </div>
            </div>
        </div>
    </section>


</body>
</html>
<!--{% for weather in weather %}-->
<!--{% endfor %}-->

the_weather/templates/filtered_history.html
{% extends "base.html" %}
{% block content %}

{% if filter %}
  <form action='' method="get">
      <h3>You can use filters</h3>
    {{ filter.form.as_p }}
    <button type="submit">Search</button>
  </form>
    {% endif %}



        <a href='{% url "weather:home" %}'>go to home page</a>
        <br>
        <a href='{% url "weather:filtered_history" %}'>See All history</a>
        <br>
        {% for weather in weather %}
        <img src="http://openweathermap.org/img/w/{{ weather.icon }}.png" width="50px" height="50px" alt="Image">
        <p>
        <span  class="title">{{ weather.name }}</span>
        <br>
        <span>{{ weather.temperature  }}°C</span>
        <br>
        <span>{{ weather.description }}</span>
            <br>
            {% load tz %}
            {% localtime on %}
        <span>{{ weather.date_created }} UTC</span>
            {% endlocaltime %}
        </p>
        <hr>
        {% endfor %}


{% if weather.has_other_pages %}
  <ul class="pagination">
    {% if weather.has_previous %}
      <li><a href="?page={{ weather.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in weather.paginator.page_range %}
      {% if weather.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if weather.has_next %}
      <li><a href="?page={{ weather.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}




{% endblock content %}

the_weather/templates/history_page.html
{% extends 'base.html' %}
{%block greetings %}
You search this cityes
{% endblock greetings %}

{% block content %}
        <a href='{% url "weather:home" %}'>go to home page</a>
        <br>
        {% for weather in weather %}
        <img src="http://openweathermap.org/img/w/{{ weather.icon }}.png" width="50px" height="50px" alt="Image">
        <p>
        <span  class="title">{{ weather.name }}</span>
        <br>
        <span>{{ weather.temperature  }}°C</span>
        <br>
        <span>{{ weather.description }}</span>
            <br>
            {% load tz %}
            {% localtime on %}
        <span>{{ weather.date_created }} UTC</span>
            {% endlocaltime %}
        </p>
        <hr>
        {% endfor %}


{% if weather.has_other_pages %}
  <ul class="pagination">
    {% if weather.has_previous %}
      <li><a href="?page={{ weather.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in weather.paginator.page_range %}
      {% if weather.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if weather.has_next %}
      <li><a href="?page={{ weather.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}




{% endblock content %}

the_weather/templates/home_page.html
{% extends 'base.html' %}
{%block greetings %}
Want to know the weather?
{% endblock greetings %}

{% block content %}
        {% if error %}
        <h3> Incorrect City name. Try again!!</h3>
        {% endif %}

        {% if inputform %}
        <form method="POST" enctype="multipart/form-data" action="">
        {% csrf_token %}
        {{ inputform.name }}
        <input type="submit" class="btn" value="Find city" size="small">
        </form>
        {% endif %}

        {% if selectform %}
        <form method="POST" enctype="multipart/form-data" action="">
        {% csrf_token %}
        {{ selectform.name }}
        <input type="submit" class="btn" value="Find city" size="small">
        </form>
        {% endif %}


        {% if weather %}

        <img src="http://openweathermap.org/img/w/{{ weather.icon }}.png" width="50px" height="50px" alt="Image">
        <p>
        <span  class="title">{{ weather.city }}</span>
        <br>
        <span>{{ weather.temperature  }}°C</span>
        <br>
        <span>{{ weather.description }}</span>
        </p>
        <hr>

        {% endif %}
        <a href='{% url "weather:filtered_history" %}'>See All history</a>
{% endblock content%}